name: "📦 Packager"
defaults:
  run:
    working-directory: plugin_quantumgraph
  

env:
  PROJECT_FOLDER: "quantumgraph"
  PYTHON_VERSION: 3.9

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  packaging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system requirements
        run: |
          sudo apt update
          sudo apt install qt5-default qttools5-dev-tools

      - name: Install project requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r requirements/packaging.txt

      - name: Update translations
        run: pylupdate5 -noobsolete -verbose ${{ env.PROJECT_FOLDER }}/resources/i18n/plugin_translation.pro

      - name: Compile translations
        run: lrelease ${{ env.PROJECT_FOLDER }}/resources/i18n/*.ts

      - name: Package the latest version
        run: qgis-plugin-ci package latest --allow-uncommitted-changes

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_FOLDER }}-latest
          path: ${{ env.PROJECT_FOLDER }}.*.zip
          if-no-files-found: error

