name: "🚀 Releaser"
defaults:
  run:
    working-directory: plugin_quantumgraph
on:
  push:
    tags: "*"
  workflow_dispatch:

env:
  PROJECT_FOLDER: "quantumgraph"
  PYTHON_VERSION: 3.9


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Get source code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install system requirements
      run: |
        sudo apt update
        sudo apt install qt5-default qttools5-dev-tools

    - name: Install Python requirements
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install -U -r requirements/packaging.txt

    - name: Compile translations
      run: lrelease ${{ env.PROJECT_FOLDER }}/resources/i18n/*.ts

    - name : Get current changelog for ${GITHUB_REF/refs\/tags\//}
      run: qgis-plugin-ci changelog ${GITHUB_REF/refs\/tags\//} >> release.md

    - name: Create release on GitHub
      uses: ncipollo/release-action@v1.10.0
      with:
        bodyFile: release.md
        generateReleaseNotes: true

    - name: Deploy plugin
      run: >-
        qgis-plugin-ci
        release ${GITHUB_REF/refs\/tags\//}
        --github-token ${{ secrets.GITHUB_TOKEN }}
        --allow-uncommitted-changes
        --create-plugin-repo

